version: '3'
services:
  pantry-fairy-db:
    image: mysql:8.0
    container_name: pantry-fairy-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pantry-fairy-password
      MYSQL_DATABASE: pantry_fairy_dev
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    restart: always
